### PR TITLE
Change the add & find instructions

### LINKED ISSUE #108: Change add command MESSAGE_USAGE
Currently, the message displayed on invalid input for the Add Command is incorrect.

image

Let's change this to suit our current usage with the NRIC prefix.

### PR DESCRIPTION
**Pull request by yitong241**
Closes #108

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/AddCommand.java [hunk 1]
```diff
@@ -1,7 +1,7 @@
 package seedu.address.logic.commands;
 
 import static java.util.Objects.requireNonNull;
-import static seedu.address.logic.parser.CliSyntax.PREFIX_NAME;
+import static seedu.address.logic.parser.CliSyntax.*;
```
Comment (nramapurath) [inline src/main/java/seedu/address/logic/commands/AddCommand.java:4]: Wouldn't it be better to explicitly import the specific PREFIX_abc?

**Review by nramapurath — CHANGES_REQUESTED** [review]
