### PR TITLE
fixes

### LINKED ISSUE #187: [PE-D][Tester E] Help link does not lead to User Guide
I think updating the link to https://ay2223s2-cs2103t-t12-2.github.io/tp/UserGuide.html can increase ease of access for the users.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: yyj-02/ped#2

### LINKED ISSUE #189: [PE-D][Tester A] Inability to create patients based on instructions
I attempted to create a new patient using `add name/testuser nric/s0012345e` and was surprised that it did not pass the check for NRIC as it seems to meet the conditions listed by the error message - to start with `S`, `T`, `F`, or `G`, followed by 7 numbers `0012345` and ending with a letter `e` as shown in the screenshot below.

I managed to resolve this by playing around and finally got it to work when i capitalise `e` to `E`. It might be better to highlight to the user about the case sensitivity, or even better, to make the check case-insensitive.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Beebeeoii/ped#1

### LINKED ISSUE #191: [PE-D][Tester E] GRAY is not a condition
I think this should be unknown

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: yyj-02/ped#3

### LINKED ISSUE #203: [PE-D][Tester E] Usage of status and condition
I think the usage of status and condition can be more consistent throughout ug and the app

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: yyj-02/ped#6

### LINKED ISSUE #208: [PE-D][Tester C] deleting a ward: UG should let users know the constraints of deleting a ward
This constraint is not reflected in the UG, perhaps adding a note to user in the UG could make it more clear to the users.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: dfordarius/ped#6

### LINKED ISSUE #210: [PE-D][Tester B] Sort patients by Status not so appropriate for UNKNOWN
When sorting patients by Status in ascending order, patients with UNKNOWN is placed at front, which might not be so  appropriate.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: WindyCall/ped#4

### LINKED ISSUE #213: [PE-D][Tester C] find : UG not consistent with text in command box
`medinfo` allows the user to find based on ward (i.e `find w/A04`), but this is not stated in the UG under the `find` section. 

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: dfordarius/ped#7

### LINKED ISSUE #219: [PE-D][Tester E] Inconsistency in UI
Website says no discharge date set
App shows To be Confirmed

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: yyj-02/ped#10

### LINKED ISSUE #227: [PE-D][Tester D] Inconsistent invalid command help messages
Description: The invalid command help messages for the optional parameters are not standardised

Problematic behavior: The optional parameters are stated to be [s/STATUS] [w/WARD] [d/DISCHARGE] in the UG, for the edit command it is [s/STATUS w/WARD d/DISCHARGE], for the add command it is [optional]s/STATUS. Should choose one of the 3 conventions and standardise throughout the UG and the application.

For more detail, please refer to the annotations on the screenshot below.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: kyueran/ped#11

### LINKED ISSUE #256: Describe delete confirmation in UG

### PR DESCRIPTION
**Pull request by jeraldkiew**
fix optional parameters message - closes #227 
add find w/ to UG - closes #213 
fix help message - closes #187 
add delete confirmation to UG - closes #256 
add sort status info to UG - closes #210 
add deleteward only for empty ward info to UG - closes #208 
fix condition to status - closes #203
closes #191 
add info on capital NRIC to UG - closes #189 
update UI photos in UG and index.md - closes #219

### CODE REVIEW

File: src/main/java/seedu/medinfo/ui/HelpWindow.java [hunk 1]
```diff
@@ -16,7 +16,7 @@
 public class HelpWindow extends UiPart<Stage> {
 
     public static final String USERGUIDE_URL = "https://ay2223s2-cs2103t-t12-2.github.io/tp/";
```
Comment (nramapurath) [inline src/main/java/seedu/medinfo/ui/HelpWindow.java:18]: Could we change this to the User Guide link instead and have the help message as "Refer to MedInfo's user guide:")?

**Review by nramapurath — COMMENTED** [review]
The changes look good. I'd recommend a minor change for the UG link in the help message

**Review by nramapurath — APPROVED** [review]
LGTM, good changes, should address many of the documentation bugs raised in PE-D

**Review by nramapurath — COMMENTED** [review]
LGTM, should fix most of our documentation bugs
